In [2]:
import json
import pandas as pd

In [3]:
with open("./data/hotels_korea_reviews_text.json", "r", encoding="utf-8") as file1 :
    temp = file1.read()
    data = json.loads(temp)
print(len(data))

9027

In [4]:
# 진남이 코드

hotel_infomations = []
reviews = []
for inner_data in data:
    body = inner_data['data']['body']
    hotel_id = body["pdpHeader"]['hotelId']
    
    propertyDescription = body["propertyDescription"]
    hotelName = propertyDescription['name']
    hotelGrade = propertyDescription['starRatingTitle']
    hotelRating = propertyDescription['starRating']
    region = propertyDescription['address'].get("region")
    locality = propertyDescription['address'].get("locality")

    ratingAspects = body["reviewContent"]['overall']["ratingAspects"]
    cleanliness = ratingAspects.get('cleanliness')
    service = ratingAspects.get('service')
    comfort = ratingAspects.get("comfort")
    condition = ratingAspects.get('condition')
    neighbourhood = ratingAspects.get('neighbourhood')
    
    hotel_information = {}
    hotel_information["hotel_id"] = hotel_id
    hotel_information["hotel_name"] = hotelName
    hotel_information["hotel_grade"] = hotelGrade
    hotel_information["n_reviews"] = hotelGrade
    hotel_information["avg_rating"] = hotelRating
    hotel_information["cleanliness"] = cleanliness
    hotel_information["service"] = service
    hotel_information["comfort"] = comfort
    hotel_information["condition"] = condition
    hotel_information["neighbourhood"] = neighbourhood
    hotel_information["region"] = region
    hotel_information["locality"] = locality
    hotel_infomations.append(hotel_information)

    

    groups = body["reviewContent"]["reviews"]["hermes"].get('groups')
    
    if groups:
        for group in groups:
            items = group['items']
            for item in items:
                review = {}
                review["hotel_id"] = hotel_id
                review["itineraryId"] = item.get('itineraryId')
                review["tripType"] = item['tripType']
                review["reviewDate"] = item['reviewDate']
                review["rating"] = item['rating']
                review["desceription"] = item['description']
                reviews.append(review)

In [5]:
df_hotel_info = pd.DataFrame(hotel_infomations)
df_hotel_info

,hotel_id,hotel_name,hotel_grade,n_reviews,avg_rating,cleanliness,service,comfort,condition,neighbourhood,region,locality
0,1041793024,상상속의집 (SangSang Hotel),3성급,3성급,3.0,8.0,7.6,8.2,7.8,8.2,경상남도,거제시
1,1041793024,상상속의집 (SangSang Hotel),3성급,3성급,3.0,8.0,7.6,8.2,7.8,8.2,경상남도,거제시
2,1041793024,상상속의집 (SangSang Hotel),3성급,3성급,3.0,8.0,7.6,8.2,7.8,8.2,경상남도,거제시
3,589827,바다마루 제주 (Badamaru Jeju),2.5성급,2.5성급,2.5,9.0,8.4,8.6,8.4,5.0,제주특별자치도,서귀포시
4,589827,바다마루 제주 (Badamaru Jeju),2.5성급,2.5성급,2.5,9.0,8.4,8.6,8.4,5.0,제주특별자치도,서귀포시
...,...,...,...,...,...,...,...,...,...,...,...,...
9022,507669,호텔 토스카나 (Hotel Toscana),4성급,4성급,4.0,9.2,9.2,9.4,9.2,7.8,제주특별자치도,서귀포시
9023,507669,호텔 토스카나 (Hotel Toscana),4성급,4성급,4.0,9.2,9.2,9.4,9.2,7.8,제주특별자치도,서귀포시
9024,718356256,평창펜션하늘숲 (Pyeongchang The Sky Forest),3성급,3성급,3.0,8.6,8.0,6.6,7.4,6.0,강원도,평창군
9025,718356256,평창펜션하늘숲 (Pyeongchang The Sky Forest),3성급,3성급,3.0,8.6,8.0,6.6,7.4,6.0,강원도,평창군
9026,1344945952,호텔플레이 (Hotel play),2.5성급,2.5성급,2.5,6.6,6.6,6.6,6.6,None,경상남도,창원시

In [7]:
df_review = pd.DataFrame(reviews)
df_review

,hotel_id,itineraryId,tripType,reviewDate,rating,desceription
0,1041793024,72009037635503,family,2020년 11월 20일,10.0,주차가 객실당 한칸씩 차고가 있는게 굉장히 특이했으며 가장 편리했음.\n간혹 차에 ...
1,1041793024,9202656047317,family,2020년 11월 14일,10.0,1. 오션뷰\n - 남해안의 어느 숙박업소가 그렇듯이 오션뷰가 좋습니다. 이 호텔...
2,1041793024,9196559102828,other,2020년 8월 11일,10.0,커플이 다녀가기에 좋은 숙소. 프라이빗함과 뷰도 갖춘 좋은 곳
3,1041793024,9201554317978,other,2020년 8월 10일,8.0,"위치와 뷰는 정말 좋습니다. 개별주차장이 생각보다 쓰기 좋았습니다. 다만, 호텔보다..."
4,1041793024,9196473456283,family,2020년 8월 7일,8.0,스탠다드 이용했어요\n방마다 차고가 있어서 편하게 짐 옮겼네요\n제가 이용한 방에 ...
...,...,...,...,...,...,...
208480,718356256,8141646862293,family,2019년 1월 19일,8.0,Pyeongchang - The Sky Forest Review: \r\nServi...
208481,718356256,8159891951288,family,2018년 12월 29일,6.0,The check-in took some time as there were none...
208482,1344945952,9196902905665,business,2020년 9월 14일,8.0,
208483,1344945952,9201269638204,business,2020년 7월 13일,2.0,
208484,1344945952,9195821601150,with-friends,2020년 5월 22일,10.0,