# pandas

In [ ]:
# pip install pandas
# conda install pandas

* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(테이블, dataframe)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json 데이터 html의 table 요소를 dataframe으로 손쉽게 변형 가능

# pandas에서 다루는 데이터타입 2가지
## 1) DataFrame : 2차원의 표형식 데이터
* python의 dict와도 비슷. 하나의 key 에 list 형태의 value가 매칭되어 있는 형태
* {key : [v1, v2, v3], key2 : [v1, v2, v3]}
## 2) Series: 1차원의 벡터형식 데이터
* python의 list, tuple, ndarray와 비슷함

In [5]:
import pandas as pd

# 데이터프레임 만들기
pd.DataFrame({key1: [value1, value2] key2 : [value1, value2]})

In [3]:
df = pd.DataFrame(
        {'이름' : ['홍길동', '둘리', '또치', '도우너'],
         '주소' : ['서울', '의정부', '고양', '성남'],
         '취미' : ['음악감상', '놀기', '달리기', '바이올린']}
        )

In [4]:
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [5]:
df.shape

(4, 3)

In [6]:
df.ndim

2

In [7]:
df['이름']

0    홍길동
1     둘리
2     또치
3    도우너
Name: 이름, dtype: object

In [8]:
df['이름'].dtype

dtype('O')

In [9]:
print(df['이름'][:2])

0    홍길동
1     둘리
Name: 이름, dtype: object

# Series 만들기
* pd.Series([리스트자료/튜플], name="컬럼명")
* 이름을 가지고 있는 list/벡터
* dataframe에서 컬럼 1개를 잘라온 형태

In [10]:
ages = pd.Series([22,53,35],name="나이")

In [11]:
ages.dtype

dtype('int64')

In [12]:
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [13]:
ages[0:2]

0    22
1    53
Name: 나이, dtype: int64

In [14]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [15]:
ages.min()

np.int64(22)

In [16]:
ages.max()

np.int64(53)

In [17]:
ages.sum()

np.int64(110)

In [18]:
ages.cumsum()

0     22
1     75
2    110
Name: 나이, dtype: int64

In [19]:
ages.mean()

np.float64(36.666666666666664)

In [20]:
ages.median()

np.float64(35.0)

# pandas에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql
* pd.read_확장자명(파일경로, 옵션)

* excel 파일 불러오기

In [2]:
df_excel = pd.read_excel("../06deep_learning/data/Online Retail.xlsx")
df_excel

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [3]:
%%time
df_excel2 = pd.read_excel("../06deep_learning/data/아파트(매매)_실거래가_20240806113828.xlsx", header=12, usecols=[1,2,3,4,5])
df_excel2

C:\Users\1\miniforge3\envs\fintech\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

CPU times: total: 13.7 s
Wall time: 13.7 s

                       시군구      번지    본번  부번                단지명
0         서울특별시 영등포구 당산동5가      42    42   0          당산삼성래미안4차
1      강원특별자치도 원주시 지정면 가곡리    1512  1512   0  원주롯데캐슬골드파크1차(5단지)
2        대구광역시 달성군 화원읍 구라리    1650  1650   0             대곡역래미안
3             광주광역시 남구 진월동   312-7   312   7                 광명
4             광주광역시 남구 진월동  331-93   331  93                 중흥
...                    ...     ...   ...  ..                ...
37575        서울특별시 송파구 장지동     849   849   0          송파파인타운3단지
37576        부산광역시 사상구 모라동     552   552   0               백양그린
37577        광주광역시 광산구 비아동   152-5   152   5                 호반
37578        부산광역시 사상구 모라동     552   552   0               백양그린
37579         대구광역시 북구 읍내동  1366-2  1366   2               칠곡보성

[37580 rows x 5 columns]

In [5]:
%%time
df_csv = pd.read_csv("../06deep_learning/data/아파트(매매)_실거래가_20240806113828.csv", header=12)
df_csv

CPU times: total: 93.8 ms
Wall time: 117 ms

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [11]:
df_json = pd.read_json("../05MACHINE_LEARNING/서울특별시_관광지입장정보_2011_2016.json")
df_json

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [18]:
df_html = pd.read_html("./data/corpList.htm")
df_html[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,한국제15호스팩,금융 지원 서비스업,기업인수합병,2024-06-26,12월,유한,NaN,서울특별시
1,에스오에스랩,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",산업용 및 차량용 라이다(LiDAR),2024-06-25,12월,정지성,홈페이지 보기,광주광역시
2,미래에셋비전스팩6호,금융 지원 서비스업,기업인수합병,2024-06-24,12월,정명훈,NaN,서울특별시
3,에이치엠씨제7호스팩,금융 지원 서비스업,기타금융,2024-06-24,12월,강신명,NaN,서울특별시
4,파라다이스,유원지 및 기타 오락관련 서비스업,"카지노, 호텔, 복합리조트",2024-06-24,12월,최종환..,홈페이지 보기,서울특별시
5,한중엔시에스,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업","수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...",2024-06-24,12월,김환식,홈페이지 보기,경상북도
6,KB제29호스팩,금융 지원 서비스업,기업인수합병,2024-06-21,12월,서영화,NaN,서울특별시
7,미래에셋비전스팩5호,금융 지원 서비스업,기업인수합병,2024-06-19,12월,김대호,NaN,서울특별시
8,씨어스테크놀로지,의료용 기기 제조업,심전도검사솔루션 입원환자모니터링솔루션,2024-06-19,12월,이영신,홈페이지 보기,경기도
9,한국제14호스팩,금융 지원 서비스업,기업인수합병,2024-06-19,12월,변성환,NaN,서울특별시
10,디비금융스팩12호,기타 금융업,기업인수 및 합병,2024-06-18,12월,김창희,NaN,서울특별시
11,라메디텍,의료용 기기 제조업,초소형 레이저 의료기기 및 미용기기,2024-06-17,12월,최종석,NaN,서울특별시
12,그리드위즈,"그외 기타 전문, 과학 및 기술 서비스업","수요관리 서비스, 전기차 충전기 모뎀 등",2024-06-14,12월,김구환,홈페이지 보기,경기도
13,다원넥스뷰,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,홈페이지 보기,경기도
14,미래에셋비전스팩4호,금융 지원 서비스업,기업인수목적회사(기타금융서비스),2024-05-29,12월,김정수,NaN,서울특별시

* DB에서 자료 읽어오기

In [6]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [2]:
# cryptography 에러 발생시
# 에러 구문 : RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

# 해결방안 cryptography 설치
!pip install cryptography

Requirement already satisfied: cryptography in c:\users\1\miniforge3\envs\fintech\lib\site-packages (45.0.3)
Requirement already satisfied: cffi>=1.14 in c:\users\1\miniforge3\envs\fintech\lib\site-packages (from cryptography) (1.17.1)
Requirement already satisfied: pycparser in c:\users\1\miniforge3\envs\fintech\lib\site-packages (from cffi>=1.14->cryptography) (2.22)

In [7]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn = engine.connect()
df_sql = pd.read_sql("exchange_rate", con=conn)
conn.close()
df_sql

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'exchange_rate' at line 1")
[SQL: exchange_rate]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [13]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/titanic")

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [ ]:
engine = create_engine("mysql+pymysql://kict20:kict20@221.155.18.165:3306/titanic")
conn = engine.connect()
passenger = pd.read_sql("p_info", con=conn)
conn.close()
passenger

In [15]:
df_excel3 = pd.read_csv("./data/Taitanic_train.csv")
df_excel3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 데이터의 일부만 보기
* 앞쪽 head(행갯수), 뒤쪽 tail(행개수)
* 기본값은 5행

* 데이터 프레임

# 판다스데이터프레임에서 일부 자료만 추출하기

* 데이터프레임의 컬럼 순서 바꾸기

# 데이터프레임에서 일부컬럼만 가져오기2
* loc :인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴
* iloc: 인덱스를 이용해 슬라이싱으로 데이터의 일부를 가져옴

In [ ]:
df.iloc[]

# 판다스데이터프레임에서 조건에 맞는 행만 가져오기
* df[df['컬럼명']]조건식 #조건이 참인 경우만 가져옴
* 조건식 연산자 <. <=. >, >=, ==, !=, &, \