In [2]:
import requests
import json
import pandas as pd

In [101]:
def unpack_data(response):
    c_list = {}
    for item in response['body']['items']:
        for key, value in zip(response['header']['columns'], item.values()) :
            c_list.setdefault(key,[]).append(value)
    df2 = pd.DataFrame(c_list)
    return df2

In [ ]:
import requests
url = "https://openapi.naver.com/v1/search/blog.json"
Cliend_Id = "TaVTw3HnrpVGJDDGj3ym"
Cliend_Pw = "46NsuGC17a"

payload = dict(query = '핀테크1', display = 10, start= 1, sort ="sim")
headers = {"X-Naver-Client-Id" : Cliend_Id, "X-Naver-Client-Secret" : Cliend_Pw }

r = requests.get(url, params=payload, headers = headers)
print(r.url)
print(r.status_code)
response = r.json()
response
r_response = pd.DataFrame(response)
r_response

In [8]:
url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
payload = {"serviceKey" : ServiceKey_d,
           "pageNo": 1,
           "numOfRows": 100,
           "divId" : "indsSclsCd",
           "key" : "I21006",
           "type" : "json"}

r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.json()
response

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=1&numOfRows=100&divId=indsSclsCd&key=I21006&type=json
200

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202412',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA010120220800082866',
    'bizesNm': '순살만공격',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41115',
    'signguNm': '수원시 팔달구',
    'adongCd': '41115730',
    'adongNm': '인계동',
    'ldongCd': '4111514100',
    'ldongNm': '인계동',
    'lnoCd': '4111514100110310016',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1031,
    'lnoSlno': 16,
    'lnoAdr': '경기도 수원시 팔달구 인계동 1031-16',
    'rdnmCd': '411154328017',
    'rdnm': '경기도 수원시 팔달구 경수대로446번길',
    'bldMnno': 60,
    'bldSlno': '',
    'bldMngNo': '4111514100110310016011790',
    'bldNm': '가하빌딩',
    'rdnmAdr': '경기도 수원시 팔달구 경수대로446번길 60',
    'oldZipcd': '442834',
    'newZipcd': '16490',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.029649885725,
    'lat': 37.2649630429687},
   {'bizesId': 'MA010120220800083008',
    'bizesNm': '가마치통닭구남점',
    'brchNm': '해운대',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26350',
    'signguNm': '해운대구',
    'adongCd': '26350530',
    'adongNm': '중1동',
    'ldongCd': '2635010600',
    'ldongNm': '중동',
    'lnoCd': '2635010600113940021',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1394,
    'lnoSlno': 21,
    'lnoAdr': '부산광역시 해운대구 중동 1394-21',
    'rdnmCd': '263504199009',
    'rdnm': '부산광역시 해운대구 구남로41번길',
    'bldMnno': 33,
    'bldSlno': '',
    'bldMngNo': '2635010600113940021021996',
    'bldNm': '일부호',
    'rdnmAdr': '부산광역시 해운대구 구남로41번길 33',
    'oldZipcd': '612847',
    'newZipcd': '48095',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 129.162500197305,
    'lat': 35.1618787147919},
   {'bizesId': 'MA010120220800061350',
    'bizesNm': '어강정이다',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28185',
    'signguNm': '연수구',
    'adongCd': '28185766',
    'adongNm': '청학동',
    'ldongCd': '2818510400',
    'ldongNm': '청학동',
    'lnoCd': '2818510400104730007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 473,
    'lnoSlno': 7,
    'lnoAdr': '인천광역시 연수구 청학동 473-7',
    'rdnmCd': '281854256320',
    'rdnm': '인천광역시 연수구 함박뫼로12번길',
    'bldMnno': 5,
    'bldSlno': 4,
    'bldMngNo': '2818510400104730007037580',
    'bldNm': '',
    'rdnmAdr': '인천광역시 연수구 함박뫼로12번길 5-4',
    'oldZipcd': '406831',
    'newZipcd': '21917',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.671921772469,
    'lat': 37.4185156217288},
   {'bizesId': 'MA010120220800079264',
    'bizesNm': '옛날통닭',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '46',
    'ctprvnNm': '전라남도',
    'signguCd': '46830',
    'signguNm': '영암군',
    'adongCd': '46830250',
    'adongNm': '영암읍',
    'ldongCd': '4683025024',
    'ldongNm': '영암읍',
    'lnoCd': '4683025024101350000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 135,
    'lnoSlno': '',
    'lnoAdr': '전라남도 영암군 영암읍 동무리 135',
    'rdnmCd': '468303295080',
    'rdnm': '전라남도 영암군 영암읍 열무정로',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '4683025024101350000017869',
    'bldNm': '',
    'rdnmAdr': '전라남도 영암군 영암읍 열무정로 5',
    'oldZipcd': '526804',
    'newZipcd': '58416',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.697730344683,
    'lat': 34.7989834368776},
   {'bizesId': 'MA010120220800079372',
    'bizesNm': '도리원통닭',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47730',
    'signguNm': '의성군',
    'adongCd': '47730380',
    'adongNm': '봉양면',
    'ldongCd': '4773038040',
    'ldongNm': '봉양면',
    'lnoCd': '4773038040100990003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 99,
    'lnoSlno': 3,
    'lnoAdr': '경상북도 의성군 봉양면 화전리 99-3',
    'rdnmCd': '477304745118',
    'rdnm': '경상북도 의성군 봉양면 도리원1길',
    'bldMnno': 66,
    'bldSlno': '',
    'bldMngNo': '4773038040100990003056372',
    'bldNm': '',
    'rdnmAdr': '경상북도 의성군 봉양면 도리원1길 66',
    'oldZipcd': '769913',
    'newZipcd': '37362',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.580987045689,
    'lat': 36.2995649406362},
   {'bizesId': 'MA010120220800083546',
    'bizesNm': '옛날통닭',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41650',
    'signguNm': '포천시',
    'adongCd': '41650340',
    'adongNm': '신북면',
    'ldongCd': '4165034021',
    'ldongNm': '신북면',
    'lnoCd': '4165034021108020003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 802,
    'lnoSlno': 3,
    'lnoAdr': '경기도 포천시 신북면 가채리 802-3',
    'rdnmCd': '416503213059',
    'rdnm': '경기도 포천시 신북면 중앙로',
    'bldMnno': 203,
    'bldSlno': '',
    'bldMngNo': '4165034021108020003036329',
    'bldNm': '',
    'rdnmAdr': '경기도 포천시 신북면 중앙로 203',
    'oldZipcd': '487911',
    'newZipcd': '11140',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.208089664038,
    'lat': 37.9033437369941},
   {'bizesId': 'MA010120220800079573',
    'bizesNm': '후라이드참잘하는집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27290',
    'signguNm': '달서구',
    'adongCd': '27290650',
    'adongNm': '본동',
    'ldongCd': '2729012400',
    'ldongNm': '본동',
    'lnoCd': '2729012400106110005',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 611,
    'lnoSlno': 5,
    'lnoAdr': '대구광역시 달서구 본동 611-5',
    'rdnmCd': '272904241620',
    'rdnm': '대구광역시 달서구 학산로7길',
    'bldMnno': 79,
    'bldSlno': '',
    'bldMngNo': '2729012400106110005009667',
    'bldNm': '',
    'rdnmAdr': '대구광역시 달서구 학산로7길 79',
    'oldZipcd': '704806',
    'newZipcd': '42727',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.530554926317,
    'lat': 35.8353404505646},
   {'bizesId': 'MA010120220800083749',
    'bizesNm': '60계치킨양산웅상점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48330',
    'signguNm': '양산시',
    'adongCd': '48330560',
    'adongNm': '평산동',
    'ldongCd': '4833011900',
    'ldongNm': '평산동',
    'lnoCd': '4833011900101100021',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 110,
    'lnoSlno': 21,
    'lnoAdr': '경상남도 양산시 평산동 110-21',
    'rdnmCd': '483303338102',
    'rdnm': '경상남도 양산시 평산로',
    'bldMnno': 45,
    'bldSlno': 7,
    'bldMngNo': '4833011900101100021000001',
    'bldNm': '',
    'rdnmAdr': '경상남도 양산시 평산로 45-7',
    'oldZipcd': '626848',
    'newZipcd': '50549',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 129.150113518398,
    'lat': 35.3814252762722},
   {'bizesId': 'MA010120220800062257',
    'bizesNm': '후라이드참잘하는집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47190',
    'signguNm': '구미시',
    'adongCd': '47190551',
    'adongNm': '도량동',
    'ldongCd': '4719010300',
    'ldongNm': '도량동',
    'lnoCd': '4719010300102270001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 227,
    'lnoSlno': 1,
    'lnoAdr': '경상북도 구미시 도량동 227-1',
    'rdnmCd': '471903308011',
    'rdnm': '경상북도 구미시 도봉로',
    'bldMnno': 76,
    'bldSlno': 53,
    'bldMngNo': '4719010300102270001000001',
    'bldNm': '',
    'rdnmAdr': '경상북도 구미시 도봉로 76-53',
    'oldZipcd': '730908',
    'newZipcd': '39202',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.31697458222,
    'lat': 36.1395078716985},
   {'bizesId': 'MA010120220800062279',
    'bizesNm': '60계치킨군포송정지구점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41410',
    'signguNm': '군포시',
    'adongCd': '41410630',
    'adongNm': '송부동',
    'ldongCd': '4141010900',
    'ldongNm': '도마교동',
    'lnoCd': '4141010900104900007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 490,
    'lnoSlno': 7,
    'lnoAdr': '경기도 군포시 도마교동 490-7',
    'rdnmCd': '414104403077',
    'rdnm': '경기도 군포시 송부로34번길',
    'bldMnno': 23,
    'bldSlno': '',
    'bldMngNo': '4141010900104900007000001',
    'bldNm': '',
    'rdnmAdr': '경기도 군포시 송부로34번길 23',
    'oldZipcd': '435070',
    'newZipcd': '15885',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.919711553136,
    'lat': 37.3152174498561},
   {'bizesId': 'MA010120220800079801',
    'bizesNm': '가마치구남점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26320',
    'signguNm': '북구',
    'adongCd': '26320520',
    'adongNm': '구포2동',
    'ldongCd': '2632010500',
    'ldongNm': '구포동',
    'lnoCd': '2632010500110860004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1086,
    'lnoSlno': 4,
    'lnoAdr': '부산광역시 북구 구포동 1086-4',
    'rdnmCd': '263204196218',
    'rdnm': '부산광역시 북구 백양대로1015번길',
    'bldMnno': 24,
    'bldSlno': '',
    'bldMngNo': '2632010500110860004001209',
    'bldNm': '',
    'rdnmAdr': '부산광역시 북구 백양대로1015번길 24',
    'oldZipcd': '616807',
    'newZipcd': '46650',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.99397452886,
    'lat': 35.1971590446343},
   {'bizesId': 'MA010120220800062481',
    'bizesNm': '네네치킨',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '43',
    'ctprvnNm': '충청북도',
    'signguCd': '43150',
    'signguNm': '제천시',
    'adongCd': '43150528',
    'adongNm': '중앙동',
    'ldongCd': '4315010100',
    'ldongNm': '의림동',
    'lnoCd': '4315010100100350002',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 35,
    'lnoSlno': 2,
    'lnoAdr': '충청북도 제천시 의림동 35-2',
    'rdnmCd': '431503239037',
    'rdnm': '충청북도 제천시 숭문로',
    'bldMnno': 100,
    'bldSlno': '',
    'bldMngNo': '4315010100100350002029552',
    'bldNm': '',
    'rdnmAdr': '충청북도 제천시 숭문로 100',
    'oldZipcd': '390030',
    'newZipcd': '27169',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.208763434527,
    'lat': 37.1418734977146},
   {'bizesId': 'MA010120220800080369',
    'bizesNm': '비에치씨',
    'brchNm': '응암점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11380',
    'signguNm': '은평구',
    'adongCd': '11380600',
    'adongNm': '응암3동',
    'ldongCd': '1138010700',
    'ldongNm': '응암동',
    'lnoCd': '1138010700105770016',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 577,
    'lnoSlno': 16,
    'lnoAdr': '서울특별시 은평구 응암동 577-16',
    'rdnmCd': '113803005055',
    'rdnm': '서울특별시 은평구 응암로',
    'bldMnno': 215,
    'bldSlno': '',
    'bldMngNo': '1138010700105770016000001',
    'bldNm': '명남더블레스아파트2차',
    'rdnmAdr': '서울특별시 은평구 응암로 215',
    'oldZipcd': '122923',
    'newZipcd': '03457',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.917049523516,
    'lat': 37.5912319434629},
   {'bizesId': 'MA010120220800063234',
    'bizesNm': '비에이치씨장흥점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '46',
    'ctprvnNm': '전라남도',
    'signguCd': '46800',
    'signguNm': '장흥군',
    'adongCd': '46800250',
    'adongNm': '장흥읍',
    'ldongCd': '4680025037',
    'ldongNm': '장흥읍',
    'lnoCd': '4680025037107340024',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 734,
    'lnoSlno': 24,
    'lnoAdr': '전라남도 장흥군 장흥읍 건산리 734-24',
    'rdnmCd': '468003292043',
    'rdnm': '전라남도 장흥군 장흥읍 중앙로',
    'bldMnno': 36,
    'bldSlno': '',
    'bldMngNo': '4680025037107340024006840',
    'bldNm': '',
    'rdnmAdr': '전라남도 장흥군 장흥읍 중앙로 36',
    'oldZipcd': '529801',
    'newZipcd': '59324',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.908012673161,
    'lat': 34.6791735204663},
   {'bizesId': 'MA010120220800080575',
    'bizesNm': '돈치킨',
    'brchNm': '신탄진점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '30',
    'ctprvnNm': '대전광역시',
    'signguCd': '30230',
    'signguNm': '대덕구',
    'adongCd': '30230560',
    'adongNm': '석봉동',
    'ldongCd': '3023011100',
    'ldongNm': '석봉동',
    'lnoCd': '3023011100103090011',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 309,
    'lnoSlno': 11,
    'lnoAdr': '대전광역시 대덕구 석봉동 309-11',
    'rdnmCd': '302302010001',
    'rdnm': '대전광역시 대덕구 대덕대로',
    'bldMnno': 1554,
    'bldSlno': '',
    'bldMngNo': '3023011100103090011023122',
    'bldNm': '',
    'rdnmAdr': '대전광역시 대덕구 대덕대로 1554',
    'oldZipcd': '306810',
    'newZipcd': '34317',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.421093474382,
    'lat': 36.4491123495732},
   {'bizesId': 'MA010120220800080617',
    'bizesNm': '지코바',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48220',
    'signguNm': '통영시',
    'adongCd': '48220670',
    'adongNm': '봉평동',
    'ldongCd': '4822011600',
    'ldongNm': '봉평동',
    'lnoCd': '4822011600100080001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 8,
    'lnoSlno': 1,
    'lnoAdr': '경상남도 통영시 봉평동 8-1',
    'rdnmCd': '482204799247',
    'rdnm': '경상남도 통영시 서송정3길',
    'bldMnno': 27,
    'bldSlno': 3,
    'bldMngNo': '4822011600100080001043809',
    'bldNm': '',
    'rdnmAdr': '경상남도 통영시 서송정3길 27-3',
    'oldZipcd': '650140',
    'newZipcd': '53073',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.420596770894,
    'lat': 34.8325370727557},
   {'bizesId': 'MA010120220800080761',
    'bizesNm': '네네치킨',
    'brchNm': '흥덕점',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41463',
    'signguNm': '용인시 기흥구',
    'adongCd': '41463516',
    'adongNm': '영덕1동',
    'ldongCd': '4146311100',
    'ldongNm': '영덕동',
    'lnoCd': '4146311100110070007',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1007,
    'lnoSlno': 7,
    'lnoAdr': '경기도 용인시 기흥구 영덕동 1007-7',
    'rdnmCd': '414633204069',
    'rdnm': '경기도 용인시 기흥구 흥덕1로',
    'bldMnno': 50,
    'bldSlno': '',
    'bldMngNo': '4146311100110070007020937',
    'bldNm': '',
    'rdnmAdr': '경기도 용인시 기흥구 흥덕1로 50',
    'oldZipcd': '446908',
    'newZipcd': '16954',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.069126617626,
    'lat': 37.2731009982926},
   {'bizesId': 'MA010120220800057431',
    'bizesNm': '비에이치씨천호대교점',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11740',
    'signguNm': '강동구',
    'adongCd': '11740610',
    'adongNm': '천호2동',
    'ldongCd': '1174010900',
    'ldongNm': '천호동',
    'lnoCd': '1174010900104580003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 458,
    'lnoSlno': 3,
    'lnoAdr': '서울특별시 강동구 천호동 458-3',
    'rdnmCd': '117402000008',
    'rdnm': '서울특별시 강동구 천호대로',
    'bldMnno': 989,
    'bldSlno': '',
    'bldMngNo': '1174010900104580003011951',
    'bldNm': '천호역한강청년주택',
    'rdnmAdr': '서울특별시 강동구 천호대로 989',
    'oldZipcd': '134874',
    'newZipcd': '05248',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.122404774553,
    'lat': 37.5394624547997},
   {'bizesId': 'MA010120220800057654',
    'bizesNm': '후라이드참잘하는집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26440',
    'signguNm': '강서구',
    'adongCd': '26440535',
    'adongNm': '명지1동',
    'ldongCd': '2644010400',
    'ldongNm': '명지동',
    'lnoCd': '2644010400133610000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 3361,
    'lnoSlno': '',
    'lnoAdr': '부산광역시 강서구 명지동 3361',
    'rdnmCd': '264403350857',
    'rdnm': '부산광역시 강서구 명지국제5로',
    'bldMnno': 60,
    'bldSlno': '',
    'bldMngNo': '2644010400116470001000001',
    'bldNm': '에일린의뜰',
    'rdnmAdr': '부산광역시 강서구 명지국제5로 60',
    'oldZipcd': '618200',
    'newZipcd': '46773',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.920886670122,
    'lat': 35.1003906643539},
   {'bizesId': 'MA010120220800058036',
    'bizesNm': '후라이드참잘하는집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I210',
    'indsMclsNm': '기타 간이',
    'indsSclsCd': 'I21006',
    'indsSclsNm': '치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41630',
    'signguNm': '양주시',

In [98]:
c_list = {}
for item in response['body']['items']:
    for key, value in item.items() :
        c_list.setdefault(key,[]).append(value)
        
df2 = pd.DataFrame(c_list)
df2

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800006500,김종용누룽지통닭,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1120010700100190046019611,행당동1,서울특별시 성동구 마조로5길 7,133817,04760,,2,,127.040371,37.559927
1,MA010120220800007898,코리안숯불닭바베큐,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4111513900102210027019153,,경기도 수원시 팔달구 세지로 369,442837,16242,,,,127.026567,37.283525
2,MA010120220800009322,페리카나치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1130510100103220025020436,,서울특별시 강북구 도봉로29길 10,142815,01176,,1,,127.027661,37.620729
3,MA010120220800001311,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111013700100490000014132,,서울특별시 종로구 삼일대로 434-1,110320,03133,,,,126.988182,37.573538
4,MA010120220800009839,매일치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016700100510000012087,,서울특별시 종로구 율곡로19길 9,110844,03100,,,,127.005411,37.575998
5,MA010120220800010432,팜카페앤드전통차,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111015300101370000017924,피카디리플러스,서울특별시 종로구 돈화문로5가길 1,110808,03139,,6,,126.991227,37.571024
6,MA010120220800012252,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111017500102010004001211,,서울특별시 종로구 종로66길 18,110825,03115,,1,,127.021791,37.574140
7,MA010120220800012332,본투비,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016200103200002012561,,서울특별시 종로구 대학로 5,110480,03129,,,,127.001721,37.571592
8,MA010120220800003146,깐부치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56194,...,4121010400113390001000001,아이플렉스상가,경기도 광명시 소하로 81,423051,14316,,1,,126.884017,37.447638
9,MA010120220800012733,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1135010200100580002019598,가운데,서울특별시 노원구 석계로1길 10,139841,01902,,1,,127.064119,37.615633

In [99]:
c_list = {}
for item in response['body']['items']:
    for key, value in zip(response['header']['columns'], item.values()) :
        c_list.setdefault(key,[]).append(value)
df2 = pd.DataFrame(c_list)
df2

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800006500,김종용누룽지통닭,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1120010700100190046019611,행당동1,서울특별시 성동구 마조로5길 7,133817,04760,,2,,127.040371,37.559927
1,MA010120220800007898,코리안숯불닭바베큐,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4111513900102210027019153,,경기도 수원시 팔달구 세지로 369,442837,16242,,,,127.026567,37.283525
2,MA010120220800009322,페리카나치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1130510100103220025020436,,서울특별시 강북구 도봉로29길 10,142815,01176,,1,,127.027661,37.620729
3,MA010120220800001311,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111013700100490000014132,,서울특별시 종로구 삼일대로 434-1,110320,03133,,,,126.988182,37.573538
4,MA010120220800009839,매일치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016700100510000012087,,서울특별시 종로구 율곡로19길 9,110844,03100,,,,127.005411,37.575998
5,MA010120220800010432,팜카페앤드전통차,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111015300101370000017924,피카디리플러스,서울특별시 종로구 돈화문로5가길 1,110808,03139,,6,,126.991227,37.571024
6,MA010120220800012252,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111017500102010004001211,,서울특별시 종로구 종로66길 18,110825,03115,,1,,127.021791,37.574140
7,MA010120220800012332,본투비,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016200103200002012561,,서울특별시 종로구 대학로 5,110480,03129,,,,127.001721,37.571592
8,MA010120220800003146,깐부치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56194,...,4121010400113390001000001,아이플렉스상가,경기도 광명시 소하로 81,423051,14316,,1,,126.884017,37.447638
9,MA010120220800012733,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1135010200100580002019598,가운데,서울특별시 노원구 석계로1길 10,139841,01902,,1,,127.064119,37.615633

In [107]:
total_pages = (response['body']['totalCount']//1000) + 1
unpack_data(response)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800006500,김종용누룽지통닭,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1120010700100190046019611,행당동1,서울특별시 성동구 마조로5길 7,133817,04760,,2,,127.040371,37.559927
1,MA010120220800007898,코리안숯불닭바베큐,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4111513900102210027019153,,경기도 수원시 팔달구 세지로 369,442837,16242,,,,127.026567,37.283525
2,MA010120220800009322,페리카나치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1130510100103220025020436,,서울특별시 강북구 도봉로29길 10,142815,01176,,1,,127.027661,37.620729
3,MA010120220800001311,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111013700100490000014132,,서울특별시 종로구 삼일대로 434-1,110320,03133,,,,126.988182,37.573538
4,MA010120220800009839,매일치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016700100510000012087,,서울특별시 종로구 율곡로19길 9,110844,03100,,,,127.005411,37.575998
5,MA010120220800010432,팜카페앤드전통차,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111015300101370000017924,피카디리플러스,서울특별시 종로구 돈화문로5가길 1,110808,03139,,6,,126.991227,37.571024
6,MA010120220800012252,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111017500102010004001211,,서울특별시 종로구 종로66길 18,110825,03115,,1,,127.021791,37.574140
7,MA010120220800012332,본투비,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016200103200002012561,,서울특별시 종로구 대학로 5,110480,03129,,,,127.001721,37.571592
8,MA010120220800003146,깐부치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56194,...,4121010400113390001000001,아이플렉스상가,경기도 광명시 소하로 81,423051,14316,,1,,126.884017,37.447638
9,MA010120220800012733,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1135010200100580002019598,가운데,서울특별시 노원구 석계로1길 10,139841,01902,,1,,127.064119,37.615633

In [111]:


page = 1
result_dfs = []
while True :
    url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    ServiceKey = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D"
    ServiceKey_d = "9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7/i3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r+OytZGorS2lwOw=="
    payload = {"serviceKey" : ServiceKey_d,
               "pageNo": page,
               "numOfRows": 10,
               "divId" : "indsSclsCd",
               "key" : "I21006",
               "type" : "json"}

    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    response = r.json()
    total_pages = (response['body']['totalCount']//1000) + 1
    result_dfs.append(unpack_data(response))
    print(f"{page}/{total_pages} 수집중: ", end="\r")
    
    if page < total_pages :
        page += 1
    else :
        break
        
result = pd.concat(result_dfs)
result = result.reset_index(drop=True)
result.to_csv("공공데이터_상권정보_20250401.csv", encoding="utf-8-sig", index=False)

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=1&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=2&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=3&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=4&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=5&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=6&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=7&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=8&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=9&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=10&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=11&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=12&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=13&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=14&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=15&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=16&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=17&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=18&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=19&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=20&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=21&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=22&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=23&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=24&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=25&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=26&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=27&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=28&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=29&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=30&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=31&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=32&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=33&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=34&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=35&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=36&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=37&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=38&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=39&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=40&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=41&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=42&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?serviceKey=9t7REJxyasIgObYHfyb5IVl89Ya4YjIgK5dUjgd7%2Fi3BSX61mJ9Kr9rOY3x4hzH5bg5oJP8r%2BOytZGorS2lwOw%3D%3D&pageNo=43&numOfRows=10&divId=indsSclsCd&key=I21006&type=json
200

In [112]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.